### ISSUE TITLE
Make TreeMap.findRectangle public

### ISSUE THREAD

**Issue by mariomarinato** [smurf667/treemaplib#3]
We're using treemaplib on our project, and we need to show a tooltip with details regarding the rectangle being pointed by the mouse, but TreeMap.findRectangle is protected, thus unreachable.

We could simply fork the lib and make it public for ourselves, but we think this would be a useful change for everyone.

**Comment by smurf667** [comment]
As discussed, subclassing can be used to avoid making this method public.
