### ISSUE TITLE
Make waiting cursor optional

### ISSUE THREAD

**Issue by mariomarinato** [smurf667/treemaplib#4]
When the component is used to display fast-changing information, with frequent updates and recalculations, the cursor keeps changing between "wait" and "arrow", leading to a flickering effect.

This change could be made optional.  If, say, "changeCursor" is false, the arrow would kept at all times.

**Comment by smurf667** [comment]
Hi @mariomarinato - thank you for these comments. I haven't actively done much on this repository. I'd welcome a merge request for both this and #3 - I'd review and merge it then.

**Comment by mariomarinato** [comment]
Oh, hi, @smurf667 ! It's good to know we could reach you.  Yeah, I was thinking of contributing to your code.  I've never done it before, so it might take a few days to get it done, but I'll surely do it.

**Comment by smurf667** [comment]
Done with #5
